### ISSUE TITLE
The linear mixed-effects model

### ISSUE THREAD

**Issue by lnxxx0712** [keithlohse/spectral_slopes_reliability#1]
Hello, I am not very clear whether you were using a linear mixed-effects model when you were fitting. Because I see in the R script "script_01_calculation_of_slopes_and_raw_PSD" that you were using the normal linear regression lm() fuction, the mathematical formula used in the article is also linear regression. I'm confused. Hope to get your answer, thank you very much!

**Comment by lnxxx0712** [comment]
@keithlohse looking forward to your reply~ ^_^

**Comment by keithlohse** [comment]
Hi @lnxxx0712 and thank you for the question. As I recall, the slopes were originally estimated via LMER but in the course of revisions our analyses became more complicated (which caused problems for the random-effects structure of the model) and we needed a direct r^2 so that model fit from the regression could be compared to the model fit results from FOOOF (whereas LMER only offers a psuedo-r^2). Thus, in the final analysis we used OLS regression for each subject:time:block at the Frontal, Central, Parietal, and Occipital electrodes (as you note in: "script_01_calculation_of_slopes_and_raw_PSD.R"). Which is conceptually equivalent to the estimates one would get from LMER, given certain assumptions about the random effects and a balanced dataset. 

Iteratively fitting a series of OLS regression models allowed us to side step the convergence issues/questions about random-effects structure, but on re-reading the paper, I can see that was not clear. I apologize for the confusion. 

Happy to discuss further but in short, the slopes were *estimated* by OLS regression and those slopes where then *analyzed* using LMER when looking at the effects of task (see: "script04_on_task_LMER_analyses.R"). I hope that helps!

**Comment by lnxxx0712** [comment]
@keithlohse That helps a lot, Thank you very much !
